pokemonTypes = {
["bulbasaur"] = {type1 = "grass", type2 = "poison"},
["ivysaur"] = {type1 = "grass", type2 = "poison"},
["venusaur"] = {type1 = "grass", type2 = "poison"},
["charmander"] = {type1 = "fire"},
["charmeleon"] = {type1 = "fire"},
["charizard"] = {type1 = "fire", type2 = "flying"},
["squirtle"] = {type1 = "water"},
["wartortle"] = {type1 = "water"},
["blastoise"] = {type1 = "water"},
["caterpie"] = {type1 = "bug"},
["metapod"] = {type1 = "bug"},
["butterfree"] = {type1 = "bug", type2 = "flying"},
["weedle"] = {type1 = "bug", type2 = "poison"},
["kakuna"] = {type1 = "bug", type2 = "poison"},
["beedrill"] = {type1 = "bug", type2 = "poison"},
["pidgey"] = {type1 = "normal", type2 = "flying"},
["pidgeotto"] = {type1 = "normal", type2 = "flying"},
["pidgeot"] = {type1 = "normal", type2 = "flying"},
["rattata"] = {type1 = "normal"},
["raticate"] = {type1 = "normal"},
["spearow"] = {type1 = "normal", type2 = "flying"},
["fearow"] = {type1 = "normal", type2 = "flying"},
["ekans"] = {type1 = "poison"},
["arbok"] = {type1 = "poison"},
["pikachu"] = {type1 = "electric"},
["raichu"] = {type1 = "electric"},
["sandshrew"] = {type1 = "ground"},
["sandslash"] = {type1 = "ground"},
["nidoran female"] = {type1 = "poison"},
["nidorina"] = {type1 = "poison"},
["nidoqueen"] = {type1 = "poison", type2 = "ground"},
["nidoran male"] = {type1 = "poison"},
["nidorino"] = {type1 = "poison"},
["nidoking"] = {type1 = "poison", type2 = "ground"},
["clefairy"] = {type1 = "fairy"},
["clefable"] = {type1 = "fairy"},
["vulpix"] = {type1 = "fire"},
["ninetales"] = {type1 = "fire"},
["jigglypuff"] = {type1 = "normal", type2 = "fairy"},
["wigglytuff"] = {type1 = "normal", type2 = "fairy"},
["zubat"] = {type1 = "poison", type2 = "flying"},
["golbat"] = {type1 = "poison", type2 = "flying"},
["oddish"] = {type1 = "grass", type2 = "poison"},
["gloom"] = {type1 = "grass", type2 = "poison"},
["vileplume"] = {type1 = "grass", type2 = "poison"},
["paras"] = {type1 = "bug", type2 = "grass"},
["parasect"] = {type1 = "bug", type2 = "grass"},
["venonat"] = {type1 = "bug", type2 = "poison"},
["venomoth"] = {type1 = "bug", type2 = "poison"},
["diglett"] = {type1 = "ground"},
["dugtrio"] = {type1 = "ground"},
["meowth"] = {type1 = "normal"},
["persian"] = {type1 = "normal"},
["psyduck"] = {type1 = "water"},
["golduck"] = {type1 = "water"},
["mankey"] = {type1 = "fighting"},
["primeape"] = {type1 = "fighting"},
["growlithe"] = {type1 = "fire"},
["arcanine"] = {type1 = "fire"},
["poliwag"] = {type1 = "water"},
["poliwhirl"] = {type1 = "water"},
["poliwrath"] = {type1 = "water", type2 = "fighting"},
["abra"] = {type1 = "psychic"},
["kadabra"] = {type1 = "psychic"},
["alakazam"] = {type1 = "psychic"},
["machop"] = {type1 = "fighting"},
["machoke"] = {type1 = "fighting"},
["machamp"] = {type1 = "fighting"},
["bellsprout"] = {type1 = "grass", type2 = "poison"},
["weepinbell"] = {type1 = "grass", type2 = "poison"},
["victreebel"] = {type1 = "grass", type2 = "poison"},
["tentacool"] = {type1 = "water", type2 = "poison"},
["tentacruel"] = {type1 = "water", type2 = "poison"},
["geodude"] = {type1 = "rock", type2 = "ground"},
["graveler"] = {type1 = "rock", type2 = "ground"},
["golem"] = {type1 = "rock", type2 = "ground"},
["ponyta"] = {type1 = "fire"},
["rapidash"] = {type1 = "fire"},
["slowpoke"] = {type1 = "water", type2 = "psychic"},
["slowbro"] = {type1 = "water", type2 = "psychic"},
["magnemite"] = {type1 = "electric", type2 = "steel"},
["magneton"] = {type1 = "electric", type2 = "steel"},
["farfetch'd"] = {type1 = "normal", type2 = "flying"},
["doduo"] = {type1 = "normal", type2 = "flying"},
["dodrio"] = {type1 = "normal", type2 = "flying"},
["seel"] = {type1 = "water"},
["dewgong"] = {type1 = "water", type2 = "ice"},
["grimer"] = {type1 = "poison"},
["muk"] = {type1 = "poison"},
["shellder"] = {type1 = "water"},
["cloyster"] = {type1 = "water", type2 = "ice"},
["gastly"] = {type1 = "ghost", type2 = "poison"},
["haunter"] = {type1 = "ghost", type2 = "poison"},
["gengar"] = {type1 = "ghost", type2 = "poison"},
["onix"] = {type1 = "rock", type2 = "ground"},
["drowzee"] = {type1 = "psychic"},
["hypno"] = {type1 = "psychic"},
["krabby"] = {type1 = "water"},
["kingler"] = {type1 = "water"},
["voltorb"] = {type1 = "electric"},
["electrode"] = {type1 = "electric"},
["exeggcute"] = {type1 = "grass", type2 = "psychic"},
["exeggutor"] = {type1 = "grass", type2 = "psychic"},
["cubone"] = {type1 = "ground"},
["marowak"] = {type1 = "ground"},
["hitmonlee"] = {type1 = "fighting"},
["hitmonchan"] = {type1 = "fighting"},
["lickitung"] = {type1 = "normal"},
["koffing"] = {type1 = "poison"},
["weezing"] = {type1 = "poison"},
["rhyhorn"] = {type1 = "ground", type2 = "rock"},
["rhydon"] = {type1 = "ground", type2 = "rock"},
["chansey"] = {type1 = "normal"},
["tangela"] = {type1 = "grass"},
["kangaskhan"] = {type1 = "normal"},
["horsea"] = {type1 = "water"},
["seadra"] = {type1 = "water"},
["goldeen"] = {type1 = "water"},
["seaking"] = {type1 = "water"},
["staryu"] = {type1 = "water"},
["starmie"] = {type1 = "water", type2 = "psychic"},
["mr. mime"] = {type1 = "psychic", type2 = "fairy"},
["scyther"] = {type1 = "bug", type2 = "flying"},
["jynx"] = {type1 = "ice", type2 = "psychic"},
["electabuzz"] = {type1 = "electric"},
["magmar"] = {type1 = "fire"},
["pinsir"] = {type1 = "bug"},
["tauros"] = {type1 = "normal"},
["magikarp"] = {type1 = "water"},
["gyarados"] = {type1 = "water", type2 = "flying"},
["lapras"] = {type1 = "water", type2 = "ice"},
["ditto"] = {type1 = "normal"},
["eevee"] = {type1 = "normal"},
["vaporeon"] = {type1 = "water"},
["jolteon"] = {type1 = "electric"},
["flareon"] = {type1 = "fire"},
["porygon"] = {type1 = "normal"},
["omanyte"] = {type1 = "rock", type2 = "water"},
["omastar"] = {type1 = "rock", type2 = "water"},
["kabuto"] = {type1 = "rock", type2 = "water"},
["kabutops"] = {type1 = "rock", type2 = "water"},
["aerodactyl"] = {type1 = "rock", type2 = "Flying"},
["snorlax"] = {type1 = "normal"},
["articuno"] = {type1 = "ice", type2 = "flying"},
["zapdos"] = {type1 = "electric", type2 = "flying"},
["moltres"] = {type1 = "fire", type2 = "flying"},
["dratini"] = {type1 = "dragon"},
["dragonair"] = {type1 = "dragon"},
["dragonite"] = {type1 = "dragon", type2 = "flying"},
["mewtwo"] = {type1 = "psychic"},
["mew"] = {type1 = "psychic"},
---------------------- SHINIES -------------------------
["shiny venusaur"] = {type1 = "grass", type2 = "poison"},
["shiny charizard"] = {type1 = "fire", type2 = "flying"},
["shiny blastoise"] = {type1 = "water"},
["shiny butterfree"] = {type1 = "bug", type2 = "flying"},
["shiny beedrill"] = {type1 = "bug", type2 = "poison"},
["shiny pidgeot"] = {type1 = "normal", type2 = "flying"},
["shiny rattata"] = {type1 = "normal"},
["shiny raticate"] = {type1 = "normal"},
["shiny fearow"] = {type1 = "flying"},
["shiny raichu"] = {type1 = "electric"},
["shiny nidoking"] = {type1 = "poison"},
["shiny ninetales"] = {type1 = "fire"},
["shiny zubat"] = {type1 = "poison", type2 = "flying"},
["shiny golbat"] = {type1 = "poison", type2 = "flying"},
["shiny oddish"] = {type1 = "grass", type2 = "poison"},
["shiny vileplume"] = {type1 = "grass"},
["shiny paras"] = {type1 = "bug", type2 = "grass"},
["shiny parasect"] = {type1 = "bug", type2 = "grass"},
["shiny venonat"] = {type1 = "bug", type2 = "poison"},
["shiny venomoth"] = {type1 = "bug", type2 = "poison"},
["shiny growlithe"] = {type1 = "fire"},
["shiny arcanine"] = {type1 = "fire"},
["shiny abra"] = {type1 = "ghost", type2 = "psychic"},
["shiny alakazam"] = {type1 = "psychic"},
["shiny machamp"] = {type1 = "fighting"},
["shiny tentacool"] = {type1 = "water", type2 = "poison"},
["shiny tentacruel"] = {type1 = "water", type2 = "poison"},
["shiny golem"] = {type1 = "rock"},
["shiny magneton"] = {type1 = "electric", type2 = "steel"},
["shiny farfetch'd"] = {type1 = "normal", type2 = "flying"},
["shiny dodrio"] = {type1 = "flying"},
["shiny grimer"] = {type1 = "poison"},
["shiny muk"] = {type1 = "poison"},
["shiny gengar"] = {type1 = "ghost", type2 = "poison"},
["shiny onix"] = {type1 = "rock", type2 = "ground"},
["shiny hypno"] = {type1 = "psychic"},
["shiny krabby"] = {type1 = "water"},
["shiny kingler"] = {type1 = "water"},
["shiny voltorb"] = {type1 = "electric"},
["shiny electrode"] = {type1 = "electric"},
["shiny cubone"] = {type1 = "ground"},
["shiny marowak"] = {type1 = "ground"},
["shiny hitmonlee"] = {type1 = "fighting"},
["shiny hitmonchan"] = {type1 = "fighting"},
["shiny rhydon"] = {type1 = "ground"},
["shiny tangela"] = {type1 = "grass"},
["shiny horsea"] = {type1 = "water"},
["shiny seadra"] = {type1 = "water"},
["shiny mr. mime"] = {type1 = "psychic", type2 = "fairy"},
["shiny scyther"] = {type1 = "bug", type2 = "flying"},
["shiny jynx"] = {type1 = "ice", type2 = "psychic"},
["shiny electabuzz"] = {type1 = "electric"},
["shiny magmar"] = {type1 = "fire"},
["shiny pinsir"] = {type1 = "bug"},
["shiny tauros"] = {type1 = "normal"},
["shiny magikarp"] = {type1 = "water"},
["shiny gyarados"] = {type1 = "water", type2 = "flying"},
["shiny ditto"] = {type1 = "normal"},
["shiny vaporeon"] = {type1 = "water"},
["shiny jolteon"] = {type1 = "electric"},
["shiny flareon"] = {type1 = "fire"},
["shiny snorlax"] = {type1 = "normal"},
["shiny dratini"] = {type1 = "dragon"},
["shiny dragonair"] = {type1 = "dragon"},
}

pokesDescription = {
["bulbasaur"] = "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokemon.",
["ivysaur"] = "When the bud on its back starts swelling, a sweet aroma wafts to indicate the flower's coming bloom.",
["venusaur"] = "There is a large flower on Venosaur's back. The flower is said to take on vivid colors if it gets plenty of nutrition and sunlight. The flower's aroma soothes the emotions of people.",
["charmander"] = "The fire on the tip of its tail is a measure of its life. If healthy, its tail burns intensely.",
["charmeleon"] = "If it becomes agitated during battle, it spouts intense flames, incinerating its surroundings.",
["charizard"] = "It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames.",
["squirtle"] = "It shelters itself in its shell, then strikes back with spouts of water at every opportunity.",
["wartortle"] = "It often hides in water to stalk unwary prey. For fast swimming, it moves its ears to maintain balance.",
["blastoise"] = "The jets of water it spouts from the rocket cannons on its shell can punch through thick steel.",
["caterpie"] = "It is covered with a green skin. When it grows, it sheds the skin, covers itself with silk, and becomes a cocoon.",
["metapod"] = "A steel-hard shell protects its tender body. It quietly endures hardships while awaiting evolution.",
["butterfree"] = "It loves the honey of flowers and can locate flower patches that have even tiny amounts of pollen.",
["weedle"] = "Often found in forests and grasslands. It has a sharp, toxic barb of around two inches on top of its head.",
["kakuna"] = "While awaiting evolution, it hides from predators under leaves and in nooks of branches.",
["beedrill"] = "Its best attack involves flying around at high speed, striking with poison needles, then flying off.",
["pidgey"] = "It is docile and prefers to avoid conflict. If disturbed, however, it can ferociously strike back.",
["pidgeotto"] = "It flies over its wide territory in search of prey, downing it with its highly developed claws.",
["pidgeot"] = "By flapping its wings with all its might, Pidgeot can make a gust of wind capable of bending tall trees.",
["rattata"] = "Cautious in the extreme, its hardy vitality lets it live in any kind of environment.",
["raticate"] = "It whittles its constantly growing fangs by gnawing on hard things. It can chew apart cinder walls.",
["spearow"] = "It flaps its small wings busily to fly. Using its beak, it searches in grass for prey.",
["fearow"] = "It has the stamina to keep flying all day on its broad wings. It fights by using its sharp beak.",
["ekans"] = "It sneaks through grass without making a sound and strikes unsuspecting prey from behind.",
["arbok"] = "The pattern on its belly appears to be a frightening face. Weak foes will flee just at the sight of the pattern.",
["pikachu"] = "It stores electricity in the electric sacs on its cheeks. When it releases pent-up energy in a burst, the electric power is equal to a lightning bolt.",
["raichu"] = "If it stores too much electricity, its behavior turns aggressive. To avoid this, it occasionally discharges excess energy and calms itself down.",
["sandshrew"] = "To protect itself from attackers, it curls up into a ball. It lives in arid regions with minimal rainfall.",
["sandslash"] = "It curls up in a ball to protect itself from enemy attacks. It also curls up to prevent heatstroke during the daytime when temperatures rise sharply.",
["nidoran female"] = "While it does not prefer to fight, even one drop of the poison it secretes from barbs can be fatal.",
["nidorina"] = "The female's horns develop slowly. Prefers physical attacks such as clawing and biting.",
["nidoqueen"] = "Its entire body is armored with hard scales. It will protect the young in its burrow with its life.",
["nidoran male"] = "It scans its surroundings by raising its ears out of the grass. Its toxic horn is for protection.",
["nidorino"] = "It is easily angered. By swinging its well-developed horn wildly, it can even punch through diamond.",
["nidoking"] = "It is recognized by its rock-hard hide and its extended horn. Be careful with the horn as it contains venom.",
["clefairy"] = "Its adorable appearance makes it popular as a pet. However, it is rare and difficult to find.",
["clefable"] = "Rarely seen by people, it is said to be drawn by the full moon to play at deserted lakes.",
["vulpix"] = "It controls balls of fire. As it grows, its six tails split from their tips to make more tails.",
["ninetales"] = "It has long been said that each of the nine tails embody an enchanted power. A long-lived Ninetales will have fur that shines like gold.",
["jigglypuff"] = "It captivates foes with its huge, round eyes, then lulls them to sleep by singing a soothing melody.",
["wigglytuff"] = "Its fur is the ultimate in luxuriousness. Sleeping alongside a Wigglytuff is simply divine. Its body expands seemingly without end when it inhales.",
["zubat"] = "Disliking sunlight, it sleeps deep in forests and caves until sundown.",
["golbat"] = "Once it starts sucking blood, it does not stop until it is full. It flies at night in search of prey.",
["oddish"] = "It often plants its root feet in the ground during the day and sows seeds as it walks about at night.",
["gloom"] = "The honey it drools from its mouth smells so atrocious, it can curl noses more than a mile away.",
["vileplume"] = "Its petals are the largest in the world. As it walks, it scatters extremely allergenic pollen.",
["paras"] = "Growing out of the bug's back are mushrooms called tochukaso. The mushrooms grow with the bug host.",
["parasect"] = "Parasect are known to infest the roots of large trees en masse and drain nutrients. When an infested tree dies, they move onto another tree all at once.",
["venonat"] = "Its eyes act as radar, enabling it to be active in darkness. The eyes can also shoot powerful beams.",
["venomoth"] = "The wings are covered with dustlike scales. Every time it flaps its wings, it looses highly toxic dust.",
["diglett"] = "It burrows through the ground at a shallow depth. It leaves raised earth in its wake, making it easy to spot.",
["dugtrio"] = "Its three heads move alternately, driving it through tough soil to depths of over 60 miles.",
["meowth"] = "All it does is sleep during the daytime. At night, it patrols its territory with its eyes aglow.",
["persian"] = "Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.",
["psyduck"] = "It is constantly wracked by a headache. When the headache turns intense, it begins using mysterious powers.",
["golduck"] = "A Pokemon that lives in lakes. It swims faster than any human swimming champion.",
["mankey"] = "It lives in treetop colonies. If one becomes enraged, the whole colony rampages for no reason.",
["primeape"] = "It grows angry if you see its eyes and gets angrier if you run. If you beat it, it gets even madder.",
["growlithe"] = "Its superb sense of smell ensures that this Pokemon won't forget any scent, no matter what. It uses its sense of smell to detect the emotions of others.",
["arcanine"] = "A Pokemon that is described in Chinese legends. It is said to race at an unbelievable speed.",
["poliwag"] = "Its slick black skin is thin and damp. A part of its internal organs can be seen through the skin as a spiral pattern.",
["poliwhirl"] = "Its body surface is always wet and slick with an oily fluid. Because of this greasy covering, it can easily slip and slide out of the clutches of any enemy in battle.",
["poliwrath"] = "Its highly developed muscles never grow fatigued, however much it exercises. This Pokemon can swim back and forth across the Pacific Ocean without effort.",
["abra"] = "A Pokemon that sleeps 18 hours a day. Observation revealed that it uses teleport to change its location.",
["kadabra"] = "It is rumored that a boy with psychic abilities suddenly transformed into KADABRA while he was assisting research into extrasensory powers.",
["alakazam"] = "While it has strong psychic abilities and high intelligence, an Alakazam muscles are very weak. It uses psychic power to move its body.",
["machop"] = "It continually undertakes strenuous training to master all forms of martial arts. Its strength lets it easily hoist a sumo wrestler onto its shoulders.",
["machoke"] = "Its muscular body is so powerful, it must wear a power-save belt to be able to regulate its motions.",
["machamp"] = "It is impossible to defend against punches and chops doled out by its four arms. Its fighting spirit flares up when it faces a tough opponent.",
["bellsprout"] = "Its bud looks like a human face. Because of the bud, it is rumored to be a type of legendary mandrake plant.",
["weepinbell"] = "A Pokemon that appears to be a plant. It captures unwary prey by dousing them with a toxic powder.",
["victreebel"] = "It pools in its mouth a fluid with a honeylike scent, which is really an acid that dissolves anything.",
["tentacool"] = "Its body is almost entirely composed of water. It ensnares its foe with its two long tentacles, then stabs with the poison stingers at their tips.",
["tentacruel"] = "It lives in complex rock formations on the ocean floor and traps prey using its 80 tentacles. Its red orbs glow when it grows excited or agitated.",
["geodude"] = "It climbs mountain paths using only the power of its arms. Because they look just like boulders lining paths, hikers may step on them without noticing.",
["graveler"] = "They descend from mountains by tumbling down steep slopes. They are so brutal, they smash aside obstructing trees and massive boulders with thunderous tackles.",
["golem"] = "It is said to live in volcanic craters on mountain peaks. Once a year, it sheds its hide and grows larger. The shed hide crumbles and returns to the soil.",
["ponyta"] = "About an hour after birth, its fiery mane and tail grow out, giving it an impressive appearance.",
["rapidash"] = "It usually canters casually in the fields and plains. But once a Rapidash turns serious, its fiery manes flare and blaze as it gallops its way up to 150 mph.",
["slowpoke"] = "It is always vacantly lost in thought, but no one knows what it is thinking about. It is good at fishing with its tail.",
["slowbro"] = "Lives lazily by the sea.",
["magnemite"] = "The units at its sides generate electromagnetic waves that keep it airborne. It feeds on electricity.",
["magneton"] = "Magneton emits a powerful magnetic force that is fatal to electronics and precision instruments. Because of this, it is said that some towns warn people to keep this Pokemon inside a pokeball.",
["farfetch'd"] = "It is always seen with a stick from a plant. Apparently, there are good sticks and bad sticks. This Pokemon occasionally fights with others over choice sticks.",
["doduo"] = "Even while eating or sleeping, one of the heads remains always vigilant for any sign of danger. When threatened, it flees at over 60 miles per hour.",
["dodrio"] = "Apparently, the heads aren't the only parts of the body that Dodrio has three of. It has three sets of hearts and lungs as well, so it is capable of running long distances without rest.",
["seel"] = "A Pokemon that lives on icebergs. It swims in the sea using the point on its head to break up ice.",
["dewgong"] = "In snow, the pure white coat covering its body obscures it from predators.",
["grimer"] = "It was born when sludge in a dirty stream was exposed to the moon's X-rays. It appears among filth.",
["muk"] = "It is usually undetectable because it blends in with the ground. Touching it can cause terrible poisoning.",
["shellder"] = "It swims backward by opening and closing its two shells. Its large tongue is always kept hanging out.",
["cloyster"] = "It fights by keeping its shell tightly shut for protection and by shooting spikes to repel foes.",
["gastly"] = "When exposed to a strong wind, a Gastly's gaseous body quickly dwindles away. They cluster under the eaves of houses to escape the ravages of wind.",
["haunter"] = "Because of its ability to slip through block walls, it is said to be from another dimension.",
["gengar"] = "Deep in the night, your shadow cast by a streetlight may suddenly overtake you. It is actually a Gengar running past you, pretending to be your shadow.",
["onix"] = "There is a magnet in its brain that prevents an Onix from losing direction while tunneling. As it grows older, its body becomes steadily rounder and smoother.",
["drowzee"] = "A descendent of the legendary animal baku, which is said to eat dreams. It is skilled at hypnotism.",
["hypno"] = "Seeing its swinging pendulum can induce sleep in three seconds, even in someone who just woke up.",
["krabby"] = "It lives in burrows dug on sandy beaches. Its pincers fully grow back if they are broken in battle.",
["kingler"] = "It waves its huge, oversized claw in the air to communicate with others. But since the claw is so heavy, this Pokemon quickly tires.",
["voltorb"] = "It looks just like a Poke Ball. It is dangerous because it may electrocute or explode on touch.",
["electrode"] = "It is known to drift on winds if it is bloated to bursting with stored electricity.",
["exeggcute"] = "Its six eggs converse using telepathy. They can quickly gather if they become separated.",
["exeggutor"] = "It is called The Walking Tropical Rainforest. Each of the nuts has a face and a will of its own.",
["cubone"] = "It pines for the mother it will never see again. Seeing a likeness of its mother in the full moon, it cries. The stains on the skull it wears are from its tears.",
["marowak"] = "MarowaK is the evolved form of a Cubone that has overcome its sadness at the loss of its mother and grown tough. This Pokemon's tempered and hardened spirit is not easily broken.",
["hitmonlee"] = "Its legs freely stretch and contract. Using these springlike limbs, it bowls over foes with devastating kicks. After battle, it rubs down its tired legs. Hitmonlee have a special passive skill.",
["hitmonchan"] = "A Hitmonchan is said to possess the spirit of a boxer who aimed to become the world champion. Having an indomitable spirit means that it will never give up.",
["lickitung"] = "Whenever it sees something unfamiliar, it always licks the object because it memorizes things by texture and taste. It is somewhat put off by sour things.",
["koffing"] = "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.",
["weezing"] = "It grows by feeding on gases released by garbage. Though very rare, triplets have been found.",
["rhyhorn"] = "Once it starts running, it doesn't stop. Its tiny brain makes it so stupid that it can't remember why it started running in the first place.",
["rhydon"] = "Its horn, which rotates like a drill, destroys tall buildings with one strike. It stands on its hind legs, and its brain is well developed.",
["chansey"] = "Chansey lay nutritionally excellent eggs every day. The eggs are so delicious, they are eagerly devoured by even those people who have lost their appetite.",
["tangela"] = "Its vines snap off easily and painlessly if they are grabbed, allowing it to make a quick getaway. The lost vines are replaced by new growth the very next day.",
["kangaskhan"] = "It raises its offspring in its belly pouch. It lets the baby out to play only when it feels safe.",
["horsea"] = "By cleverly flicking the fins on its back side to side, it moves in any direction while facing forward. It spits ink to escape if it senses danger.",
["seadra"] = "The poisonous barbs all over its body are highly valued as ingredients for making traditional herbal medicine. It shows no mercy to anything approaching its nest.",
["goldeen"] = "Its dorsal and pectoral fins are strongly developed like muscles. It can swim at a speed of five knots.",
["seaking"] = "Punches holes in boulders on stream-beds. This is a clever innovation that prevents its eggs from being attacked or washed away by the current.",
["staryu"] = "It gathers with others in the night and makes its red core glow on and off with the twinkling stars. It can regenerate limbs if they are severed from its body.",
["starmie"] = "At the center of its body is a red core, which sends mysterious radio signals into the night sky.",
["mr. mime"] = "It is a pantomime expert that can create invisible but solid walls using miming gestures.",
["scyther"] = "Its blindingly fast speed adds to the sharpness of its twin forearm scythes. The scythes can slice through thick logs in one wicked stroke.",
["jynx"] = "Its cries sound like human speech. However, it is impossible to tell what it is trying to say.",
["electabuzz"] = "Half of all blackouts occur when this Pokemon appears at power plants and eats electricity.",
["magmar"] = "Born in the spout of a volcano, its body is covered by flames that shimmer like the sun.",
["pinsir"] = "It grips prey with its pincers until the prey is torn in half. What it can't tear, it tosses far.",
["tauros"] = "Once it takes aim at its foe, it makes a headlong charge. It is famous for its violent nature.",
["magikarp"] = "It is said to be the world's weakest Pokemon. No one knows why it has managed to survive.",
["gyarados"] = "Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage.",
["lapras"] = "It loves crossing the sea with people and Pokemon on its back. It understands human speech.",
["ditto"] = "It has the ability to reconstitute its entire cellular structure to transform into whatever it sees.",
["eevee"] = "A rare Pokemon that adapts to harsh environments by taking on different evolutionary forms.",
["vaporeon"] = "It has evolved to be suitable for an aquatic life. It can invisibly melt away into water.",
["jolteon"] = "It controls 10,000-volt power and can raise all the fur on its body as if it were sharp needles.",
["flareon"] = "It has a flame sac in its body. Its body temperature tops 1,650 degrees Fahrenheit before battle.",
["porygon"] = "The world's first artificially created Pokemon. It can travel through electronic space.",
["omanyte"] = "A Pokemon that was resurrected from a fossil using modern science. It swam in ancient seas.",
["omastar"] = "It is thought that this Pokemon became extinct because its spiral shell grew too large.",
["kabuto"] = "It is thought to have inhabited beaches 300 million years ago. It is protected by a stiff shell.",
["kabutops"] = "It is thought that this Pokemon came onto land because its prey adapted to life on land.",
["aerodactyl"] = "A Pokemon that roamed the skies in the dinosaur era. Its teeth are like saw blades.",
["snorlax"] = "Snorlax's typical day consists of nothing more than eating and sleeping. It is such a docile Pokemon that there are children who use its big belly as a place to play.",
["articuno"] = "Articuno is a legendary bird Pokemon that can control ice. The flapping of its wings chills the air. As a result, it is said that when this POKeMON flies, snow will fall.",
["zapdos"] = "Zapdos is a legendary bird POKeMON that has the ability to control electricity. It usually lives in thunderclouds. The Pokemon gains power if it is stricken by lightning bolts.",
["moltres"] = "Moltres is a legendary bird Pokemon that has the ability to control fire. If this Pokemon is injured, it is said to dip its body in the molten magma of a volcano to burn and heal itself.",
["dratini"] = "It is called the Mirage Pokemon because so few have seen it. Its shed skin has been found.",
["dragonair"] = "If its body takes on an aura, the weather changes instantly. It is said to live in seas and lakes.",
["dragonite"] = "It is said to make its home somewhere in the sea. It guides crews of shipwrecks to shore.",
["mewtwo"] = "Mewtwo is a Pokemon that was created by genetic manipulation. However, even though the scientific power of humans created this Pokemon's body, they failed to endow MEWTWO with a compassionate heart.",
["mew"] = "Because it can use all kinds of moves, many scientists believe Mew to be the ancestor of Pokemon.",
-------------------------------------------------------- SHINIES --------------------------------------------------------
["shiny venusaur"] = "An Ancient Venusaur, very difficult to be found. There is a large flower on Venosaur's back. The flower is said to take on vivid colors if it gets plenty of nutrition and sunlight. The flower's aroma soothes the emotions of people.",
["shiny charizard"] = "The Charicific Valley is a training ground for Charizards so they can become stronger. It is distinguishable by its rock formation in the shape of a Elder Charizard. ",
["shiny blastoise"] = "An Ancient Blastoise, very difficult to be found. The jets of water it spouts from the rocket cannons on its shell can punch through thick steel.",
["shiny butterfree"] = "A Pink Butterfree, it loves the honey of flowers and can locate flower patches that have even tiny amounts of pollen.",
["shiny beedrill"] = "Enraged Beedrill, A Beedrill in anger evolved into red. Its best attack involves flying around at high speed, striking with poison needles, then flying off.",
["shiny pidgeot"] = "A very rare pidgeot. By flapping its wings with all its might, Pidgeot can make a gust of wind capable of bending tall trees.",
["shiny rattata"] = "A rare blue Rattata. Cautious in the extreme, its hardy vitality lets it live in any kind of environment.",
["shiny raticate"] = "A rare blue Raticate. It whittles its constantly growing fangs by gnawing on hard things. It can chew apart cinder walls.",
["shiny fearow"] = "The Shiny Pokemon of the Wingeon clan, with its huge and magnificent wings, its the unique pure flying Pokemon.",
["shiny raichu"] = "An Ultra Rare and powerful Raichu. He was trained by the best masters of electricity. His training was so intense that it skin became red. Today, he is homeless, looking for a new master capable of dominating it.",
["shiny nidoking"] = "The Shiny Pokemon of the Malefic clan, its extended horn contains the most dangerous venom, showing its enemies that it is pure poison.",
["shiny ninetales"] = "A Blue legendary Ninetales casts a sinister light from its bright green eyes to gain total control of the battle. This Pokemon is said to live for a thousand years. ",
["shiny zubat"] = "A rare dark Zubat. Disliking sunlight, it sleeps deep in forests and caves until sundown.",
["shiny golbat"] = "A rare blackwing golbat. Once it starts sucking blood, it does not stop until it is full. It flies at night in search of prey.",
["shiny oddish"] = "A rare pink Oddish. It often plants its root feet in the ground during the day and sows seeds as it walks about at night.",
["shiny vileplume"] = "Its petals are the largest in the world. As it walks, it scatters extremely allergenic pollen.",
["shiny paras"] = "A rare green Paras. Growing out of the bug's back are mushrooms called tochukaso. The mushrooms grow with the bug host.",
["shiny parasect"] = "A rare green Parasect. Parasect are known to infest the roots of large trees en masse and drain nutrients. When an infested tree dies, they move onto another tree all at once.",
["shiny venonat"] = "Ultra rare Venonat, blue eyes and white hands. Its eyes act as radar, enabling it to be active in darkness. The eyes can also shoot powerful beams.",
["shiny venomoth"] = "Ultra rare White Venomoth. The wings are covered with dustlike scales. Every time it flaps its wings, it looses highly toxic dust.",
["shiny growlithe"] = "Rare Growlithe. Its superb sense of smell ensures that this Pokemon won't forget any scent, no matter what. It uses its sense of smell to detect the emotions of others.",
["shiny arcanine"] = "It is a war dog, the scar on his face proves his courage. Pokemon that is described in Chinese legends. It is said to race at an unbelievable speed.",
["shiny abra"] = "An Abra dominated by darkness, has a strength unusual for his species. Very hard to find, and impossible to be defeated.",
["shiny alakazam"] = "A rare alakazam covered by darkness. While it has strong psychic abilities and high intelligence, an Alakazam muscles are very weak. It uses psychic power to move its body.",
["shiny machamp"] = "It is impossible to defend against punches and chops doled out by its four arms. Its fighting spirit flares up when it faces a tough opponent.",
["shiny tentacool"] = "An emerald Tentacool. Its body is almost entirely composed of water. It ensnares its foe with its two long tentacles, then stabs with the poison stingers at their tips.",
["shiny tentacruel"] = "An emerald Tentacruel. It lives in complex rock formations on the ocean floor and traps prey using its 80 tentacles. Its green orbs glow when it grows excited or agitated.",
["shiny golem"] = "It is said to live in volcanic craters on mountain peaks. Once a year, it sheds its hide and grows larger. The shed hide crumbles and returns to the soil.",
["shiny magneton"] = "Three Giant shiny Magnemite are linked by a strong magnetic force. Earaches will occur if you get too close. ",
["shiny farfetch'd"] = "Trained by the greatest Kanto's thieves, this Farfetch'd has skills superior to others of it specie.",
["shiny dodrio"] = "This unique Dodrio uses its three brains to execute complex plans. While two heads sleep, one head is said to stay awake. ",
["shiny grimer"] = "Chocolat Grimer. It was born when a chocolat was exposed to the moon's X-rays. It appears among filth.",
["shiny muk"] = "Chocolat Muk. It is usually undetectable because it blends in with the ground. Touching it can cause terrible poisoning.",
["shiny gengar"] = "Deep in the night, your shadow cast by a streetlight may suddenly overtake you. It is actually a Gengar running past you, pretending to be your shadow.",
["shiny onix"] = "Besides being made of crystal, the Crystal Onix is unique from other Onix in that it can live in water without being hurt by it. Its glass skin also gives it a special resistance to Water-type attacks.",
["shiny hypno"] = "Seeing its swinging pendulum can induce sleep in three seconds, even in someone who just woke up.",
["shiny krabby"] = "A rare blue Krabby. It lives in burrows dug on sandy beaches. Its pincers fully grow back if they are broken in battle.",
["shiny kingler"] = "A rare blue Kingler. It waves its huge, oversized claw in the air to communicate with others. But since the claw is so heavy, this Pokemon quickly tires.",
["shiny voltorb"] = "A rare green Voltorb. It looks just like a Poke Ball. It is dangerous because it may electrocute or explode on touch.",
["shiny electrode"] = "A rare green Electrode. It is known to drift on winds if it is bloated to bursting with stored electricity.",
["shiny cubone"] = "A blue skin cubone. It pines for the mother it will never see again. Seeing a likeness of its mother in the full moon, it cries. The stains on the skull it wears are from its tears.",
["shiny marowak"] = "A blue skin marowak. Marowak is the evolved form of a Cubone that has overcome its sadness at the loss of its mother and grown tough. This Pokemon's tempered and hardened spirit is not easily broken.",
["shiny hitmonlee"] = "Its legs freely stretch and contract. Using these springlike limbs, it bowls over foes with devastating kicks. After battle, it rubs down its tired legs. Hitmonlee have a special passive skill.",
["shiny hitmonchan"] = "A Hitmonchan is said to possess the spirit of a boxer who aimed to become the world champion. Having an indomitable spirit means that it will never give up.",
["shiny rhydon"] = "A golden and bright Rhydon, it walks on its hind legs. Shows signs of intelligence. Its armor-like hide even repels molten lava. ",
["shiny tangela"] = "A rare shiny tangela. Its vines snap off easily and painlessly if they are grabbed, allowing it to make a quick getaway. The lost vines are replaced by new growth the very next day.",
["shiny horsea"] = "Celestial Horsea, ultra rare. By cleverly flicking the fins on its back side to side, it moves in any direction while facing forward. It spits ink to escape if it senses danger.",
["shiny seadra"] = "Celestial Seadra, ultra rare. The poisonous barbs all over its body are highly valued as ingredients for making traditional herbal medicine. It shows no mercy to anything approaching its nest.",
["shiny mr. mime"] = "Its a rare Mr.Mime, its fingertips emit a peculiar force field that hardens air to create an actual barrier.",
["shiny scyther"] = "A warrior Scyther, has its body marked with dye of its Indian masters. Much more powerful than others of its species. ",
["shiny jynx"] = "A blue Jynx, the lady of ice that dominates the Seafrom Islands.",
["shiny electabuzz"] = "An white electabuzz. Has it body surrounded by electricity.",
["shiny magmar"] = "This special Magmar has the strength of a Volcano, it can withstand even the heat of the core of the earth!",
["shiny pinsir"] = "A rare enraged red pinsir. It grips prey with its pincers until the prey is torn in half. What it can't tear, it tosses far.",
["shiny tauros"] = "This Shiny Tauros is famous for its violent nature and it is also the leader of its herd, It can lead them in an stampede!",
["shiny magikarp"] = "A Golden Magikarp, very rare and very valuable.",
["shiny gyarados"] = "Results of an experiment, the red Gyarados is now the most feared of the seas. Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage.",
["shiny ditto"] = "It has the ability to reconstitute its entire cellular structure to transform into whatever it sees.",
["shiny vaporeon"] = "It has evolved to be suitable for an aquatic life. It can invisibly melt away into water.",
["shiny jolteon"] = "It controls 10,000-volt power and can raise all the fur on its body as if it were sharp needles.",
["shiny flareon"] = "It has a flame sac in its body. Its body temperature tops 1,650 degrees Fahrenheit before battle.",
["shiny snorlax"] = "Snorlax's typical day consists of nothing more than eating and sleeping. It is such a docile Pokemon that there are children who use its big belly as a place to play.",
["shiny dratini"] = "A Golden Dratini. It is called the Mirage Pokemon because so few have seen it. Its shed skin has been found.",
["shiny dragonair"] = "A golden Dragonair. If its body takes on an aura, the weather changes instantly. It is said to live in seas and lakes.",
}

specialabilities = {
["rock smash"] = {"Shiny Magcargo", "Shiny Sandslash", "Shiny Rhydon", "Nidoking", "Nidoqueen", "Dragonite", "Salamence", "Shiny Salamence", "Sandshrew", "Sandslash", "Diglett", "Dugtrio", "Primeape", "Machop", "Machoke", "Machamp", "Geodude", "Graveler", "Golem" , "Onix", "Cubone", "Marowak", "Rhyhorn", "Rhydon", "Kangaskhan", "Tauros", "Snorlax", "Poliwrath", "Hitmonlee", "Hitmonchan", "Aerodactyl", "Blastoise","Shiny Nidoking", "Shiny Dragonite", "Shiny Golem", "Shiny Onix", "Shiny Cubone", "Shiny Marowak", "Shiny Snorlax", "Shiny Hitmonlee", "Shiny Hitmontop", "Shiny Hitmonchan", "Shiny Blastoise", "Typhlosion", "Feraligatr", "Furret", "Ledian", "Ampharos", "Politoed", "Quagsire", "Forretress", "Steelix", "Snubbull", "Granbull", "Sudowoodo", "Gligar", "Scizor", "Heracross", "Sneasel", "Ursaring", "Teddiursa", "Slugma", "Magcargo", "Piloswine", "Swinub", "Corsola", "Phanpy", "Donphan", "Tyrogue", "Hitmontop", "Miltank", "Blissey", "Tyranitar", "Pupitar"},
["cut"] = {"Shiny Magcargo", "Shiny Crobat", "Shiny Weezing", "Shiny Sandslash", "Kabutops", "Raticate", "Bulbasaur", "Ivysaur", "Venusaur", "Charmeleon", "Charizard", "Sandshrew", "Sandslash", "Gloom", "Vileplume", "Paras", "Parasect", "Meowth", "Persian", "Bellsprout", "Weepinbell", "Victreebel", "Farfetch'd", "Krabby", "Kingler", "Exeggutor", "Tropius", "Cubone", "Marowak", "Tangela", "Scyther", "Pinsir", "Shiny Raticate", "Shiny Venusaur", "Shiny Charizard", "Shiny Vileplume", "Shiny Paras", "Shiny Parasect", "Shiny Farfetch'd", "Shiny Krabby", "Shiny Kingler", "Shiny Cubone", "Shiny Marowak", "Shiny Tangela", "Shiny Scyther", "Shiny Pinsir", "Chikorita", "Bayleef", "Meganium", "Croconow", "Feraligatr", "Furret", "Bellossom", "Hoppip", "Skiploom", "Jumpluff", "Sunkern", "Sunflora", "Scizor", "Heracross", "Sneasel", "Teddiursa", "Ursaring", "Gligar", "Skarmory"},
["light"] = {"Shiny Lanturn", "Shiny Xatu", "Shiny Magmortar", "Shiny Electivire", "Electivire", "Shiny Espeon", "Shiny Electrode", "Abra", "Kadabra", "Alakazam", "Magnemite", "Magneton", "Magnezone", "Drowzee", "Hypno", "Voltorb", "Electrode", "Mrmime", "Electabuzz", "Jolteon", "Porygon", "Pikachu", "Raichu", "Shiny Abra", "Shiny Alakazam", "Shiny Hypno", "Shiny Voltorb", "Shiny Electrode", "Shiny Electabuzz", "Shiny Jolteon", "Shiny Raichu", "Chinchou", "Lanturn", "Pichu", "Natu", "Xatu", "Mareep", "Flaaffy", "Ampharos", "Espeon", "Porygon2", "Elekid"}, 
["digholes"] = {"468", "481", "483"},
["ghostwalk"] = {"Shiny Abra", "Gastly", "Haunter", "Gengar", "Shiny Gengar", "Misdreavus"},
["dig"] = {"Shiny Magcargo", "Shiny Lanturn", "Poliwrath", "Miltank", "Shiny Sandslash", "Shiny Dodrio", "Shiny Umbreon", "Shiny Espeon", "Shiny Ninetales", "Shiny Rhydon", "Raticate", "Sandshrew", "Sandslash", "Diglett", "Dugtrio", "Primeape", "Machop", "Machoke", "Machamp", "Geodude", "Graveler", "Golem" , "Onix", "Cubone", "Marowak", "Rhyhorn", "Rhydon", "Kangaskhan", "Tauros", "Snorlax", "Eevee", "Flareon", "Jolteon", "Vaporeon", "Vulpix", "Ninetales", "Nidorina", "Nidoqueen", "Nidorino", "Nidoking", "Persian", "Arcanine", "Shiny Raticate", "Shiny Golem" , "Shiny Onix", "Shiny Cubone", "Shiny Marowak", "Shiny Snorlax", "Shiny Flareon", "Shiny Jolteon", "Shiny Vaporeon", "Shiny Nidoking", "Shiny Arcanine", "Typhlosion", "Feraligatr", "Furret", "Espeon", "Umbreon", "Ledian", "Sudowoodo", "Politoed", "Quagsire", "Gligar", "Steelix", "Snubbull", "Granbull", "Heracross", "Dunsparce", "Sneasel", "Teddiursa", "Ursaring", "Piloswine", "Hitmontop", "Larvitar", "Pupitar", "Tyranitar"},
["blink"] = {"Shiny Xatu", "Exeggutor", "Shiny Abra", "Shiny Espeon", "Shiny Mr. Mime", "Jynx", "Shiny Jynx", "Hypno", "Shiny Hypno", "Slowking", "Natu", "Xatu", "Espeon", "Mew", "Mewtwo", "Abra", "Kadabra", "Alakazam", "Porygon", "Shiny Abra", "Shiny Alakazam", "Porygon2", "Mr. Mime"},
["teleport"] = {"Shiny Xatu", "Jynx", "Shiny Jynx", "Slowking", "Slowbro", "Exeggutor", "Shiny Mr. Mime", 'Mew', 'Mewtwo', 'Abra', 'Kadabra', 'Alakazam', 'Drowzee', 'Hypno', 'Mr. Mime', 'Porygon', 'Shiny Abra', 'Shiny Alakazam', 'Shiny Hypno', 'Porygon2'},
["fly"] = {"Scyther", "Dragonair", "Porygon", "Aerodactyl", "Dragonite", "Charizard", "Pidgeot", "Fearow", "Zapdos", "Moltres", "Articuno", "Mew", "Mewtwo", "Gengar", "Farfetch'd"},
["ride"] = {"Absol", "Manectric", "Shiny Meganium", "Girafarig", "Shiny Dodrio", "Absol", "Metagross", "Shiny Ninetales", "Shiny Onix", "Venusaur", "Ninetales", "Arcanine", "Ponyta", "Rapidash", "Doduo", "Dodrio", "Onix", "Rhyhorn", "Tauros", "Shiny Venusaur", "Shiny Arcanine", "Steelix", "Houndoom", "Meganium", "Bayleef", "Stantler", "Mareep", "Piloswine"},
["surf"] = {"Swampert", "Sealeo", "Walrein","Crawdaunt", "Lombre", "Ludicolo", 'Poliwag', 'Poliwhirl', 'Seaking', 'Milotic', 'Dewgong', 'Wailord', 'Blastoise', 'Tentacruel', 'Lapras', 'Gyarados', 'Omastar', 'Kabutops', 'Vaporeon', 'Staryu', 'Starmie', 'Goldeen', 'Seadra', 'Golduck', 'Squirtle', 'Wartortle', 'Tentacool', 'Poliwrath', 'Shiny Blastoise', 'Shiny Tentacruel', 'Shiny Gyarados', 'Shiny Vaporeon', 'Shiny Seadra', 'Shiny Tentacool', "Mantine", "Totodile", "Croconow", "Feraligatr", "Marill", "Azumarill", "Quagsire", "Wooper", "Octillery", "Kingdra"},
["foresight"] = {"Machamp", "Shiny Hitmonchan", "Shiny Hitmonlee", "Shiny Hitmontop", "Hitmontop", "Hitmonlee", "Hitmonchan"},
["counter"] = {"Shiny Magcargo", "Shiny Lanturn", "Shiny Magmar", "Shiny Magmortar", "Shiny Electivire", "Machamp", "Machoke", "Hitmonchan", "Hitmonlee", "Magmar", "Electabuzz", "Scyther", "Snorlax", "Kangaskhan", "Arcanine", "Shiny Arcanine", "Shiny Snorlax", "Shiny Scyther", "Shiny Hitmonchan", "Shiny Hitmonlee", "Shiny Electabuzz", "Hitmontop", "Shiny Hitmontop"}, 
["levitate"] = {"Gengar", "Shiny Gengar"},
["evasion"] = {"Mega Scizor", "Beedrill", "Shiny Beedrill", "Scyther", "Scizor", "Hitmonlee", "Hitmonchan", "Hitmontop", "Tyrogue", "Shiny Scyther", "Shiny Hitmonchan", "Shiny Hitmonlee", "Shiny Hitmontop", "Ledian", "Ledyba", "Sneasel"},
["control mind"] = {'Haunter', 'Gengar', 'Tentacruel', 'Alakazam', 'Shiny Tentacruel', 'Shiny Gengar', 'Shiny Alakazam', 'Slowking'},
["transform"] = {"Ditto"},
["levitate_fly"] = {"Gengar", "Shiny Gengar", "Raichu", "Shiny Raichu"},
["Illusion"] = {"Misdreavus, Stantler, Shiny Stantler"},
["headbutt"] = {"Shiny Magcargo", "Shiny Crobat", "Shiny Weezing", "Shiny Sandslash", "Kabutops", "Raticate", "Bulbasaur", "Ivysaur", "Venusaur", "Charmeleon", "Charizard", "Sandshrew", "Sandslash", "Gloom", "Vileplume", "Paras", "Parasect", "Meowth", "Persian", "Bellsprout", "Weepinbell", "Victreebel", "Farfetch'd", "Krabby", "Kingler", "Exeggutor", "Tropius", "Cubone", "Marowak", "Tangela", "Scyther", "Pinsir", "Shiny Raticate", "Shiny Venusaur", "Shiny Charizard", "Shiny Vileplume", "Shiny Paras", "Shiny Parasect", "Shiny Farfetch'd", "Shiny Krabby", "Shiny Kingler", "Shiny Cubone", "Shiny Marowak", "Shiny Tangela", "Shiny Scyther", "Shiny Pinsir", "Chikorita", "Bayleef", "Meganium", "Croconow", "Feraligatr", "Furret", "Bellossom", "Hoppip", "Skiploom", "Jumpluff", "Sunkern", "Sunflora", "Scizor", "Heracross", "Sneasel", "Teddiursa", "Ursaring", "Gligar", "Skarmory", "Shiny Magcargo", "Shiny Sandslash", "Shiny Rhydon", "Nidoking", "Nidoqueen", "Dragonite", "Salamence", "Shiny Salamence", "Sandshrew", "Sandslash", "Diglett", "Dugtrio", "Primeape", "Machop", "Machoke", "Machamp", "Geodude", "Graveler", "Golem" , "Onix", "Cubone", "Marowak", "Rhyhorn", "Rhydon", "Kangaskhan", "Tauros", "Snorlax", "Poliwrath", "Hitmonlee", "Hitmonchan", "Aerodactyl", "Blastoise","Shiny Nidoking", "Shiny Dragonite", "Shiny Golem", "Shiny Onix", "Shiny Cubone", "Shiny Marowak", "Shiny Snorlax", "Shiny Hitmonlee", "Shiny Hitmontop", "Shiny Hitmonchan", "Shiny Blastoise", "Typhlosion", "Feraligatr", "Furret", "Ledian", "Ampharos", "Politoed", "Quagsire", "Forretress", "Steelix", "Snubbull", "Granbull", "Sudowoodo", "Gligar", "Scizor", "Heracross", "Sneasel", "Ursaring", "Teddiursa", "Slugma", "Magcargo", "Piloswine", "Swinub", "Corsola", "Phanpy", "Donphan", "Tyrogue", "Hitmontop", "Miltank", "Blissey", "Tyranitar", "Pupitar"},
}

pokemonPassives = {'ghostwalk', 'foresight', 'counter', 'levitate', 'evasion', 'levitate_fly', 'Illusion'}

pokemonId = {"bulbasaur", "ivysaur", "venusaur", "charmander", "charmeleon", "charizard", "squirtle", "wartortle", "blastoise", "caterpie", "metapod", "butterfree", "weedle", "kakuna", "beedrill", "pidgey", "pidgeotto", "pidgeot", "rattata", "raticate", "spearow", "fearow", "ekans", "arbok", "pikachu", "raichu", "sandshrew", "sandslash", "nidoran female", "nidorina", "nidoqueen", "nidoran male", "nidorino", "nidoking", "clefairy", "clefable", "vulpix", "ninetales", "jigglypuff", "wigglytuff", "zubat", "golbat", "oddish", "gloom", "vileplume", "paras", "parasect", "venonat", "venomoth", "diglett", "dugtrio", "meowth", "persian", "psyduck", "golduck", "mankey", "primeape", "growlithe", "arcanine", "poliwag", "poliwhirl", "poliwrath", "abra", "kadabra", "alakazam", "machop", "machoke", "machamp", "bellsprout", "weepinbell", "victreebel", "tentacool", "tentacruel", "geodude", "graveler", "golem", "ponyta", "rapidash", "slowpoke", "slowbro", "magnemite", "magneton", "farfetch'd", "doduo", "dodrio", "seel", "dewgong", "grimer", "muk", "shellder", "cloyster", "gastly", "haunter", "gengar", "onix", "drowzee", "hypno", "krabby", "kingler", "voltorb", "electrode", "exeggcute", "exeggutor", "cubone", "marowak", "hitmonlee", "hitmonchan", "lickitung", "koffing", "weezing", "rhyhorn", "rhydon", "chansey", "tangela", "kangaskhan", "horsea", "seadra", "goldeen", "seaking", "staryu", "starmie", "mr. mime", "scyther", "jynx", "electabuzz", "magmar", "pinsir", "tauros", "magikarp", "gyarados", "lapras", "ditto", "eevee", "vaporeon", "jolteon", "flareon", "porygon", "omanyte", "omastar", "kabuto", "kabutops", "aerodactyl", "snorlax", "articuno", "zapdos", "moltres", "dratini", "dragonair", "dragonite", "mewtwo", "mew"}

shinyPokemons = {"venusaur", "charizard", "blastoise", "butterfree", "beedrill", "pidgeot", "rattata", "raticate", "fearow", "raichu", "nidoking", "ninetales", "zubat", "golbat", "oddish", "vileplume", "paras", "parasect", "venonat", "venomoth", "growlithe", "arcanine", "abra", "alakazam", "machamp", "tentacool", "tentacruel", "golem", "magneton", "farfetch'd", "dodrio", "grimer", "muk", "gengar", "onix", "hypno", "krabby", "kingler", "voltorb", "electrode", "cubone", "marowak", "hitmonlee", "hitmonchan", "rhydon", "tangela", "horsea", "seadra", "mr. mime", "scyther", "jynx", "electabuzz", "magmar", "pinsir", "tauros", "magikarp", "gyarados", "ditto", "vaporeon", "jolteon", "flareon", "snorlax", "dratini", "dragonair"}

pokemonsOutfit = {
["bulbasaur"] = 25,
["ivysaur"] = 24,
["venusaur"] = 22,
["charmander"] = 29,
["charmeleon"] = 23,
["charizard"] = 67,
["squirtle"] = 2,
["wartortle"] = 6,
["blastoise"] = 55,
["caterpie"] = 32,
["metapod"] = 31,
["butterfree"] = 40,
["weedle"] = 21,
["kakuna"] = 60,
["beedrill"] = 45,
["pidgey"] = 30,
["pidgeotto"] = 5,
["pidgeot"] = 80,
["rattata"] = 36,
["raticate"] = 69,
["spearow"] = 27,
["fearow"] = 17,
["ekans"] = 7,
["arbok"] = 8,
["pikachu"] = 59,
["raichu"] = 50,
["sandshrew"] = 43,
["sandslash"] = 115,
["nidoran female"] = 70,
["nidorina"] = 71,
["nidoqueen"] = 79,
["nidoran male"] = 66,
["nidorino"] = 78,
["nidoking"] = 35,
["clefairy"] = 73,
["clefable"] = 68,
["vulpix"] = 62,
["ninetales"] = 114,
["jigglypuff"] = 63,
["wigglytuff"] = 64,
["zubat"] = 44,
["golbat"] = 122,
["oddish"] = 56,
["gloom"] = 74,
["vileplume"] = 89,
["paras"] = 81,
["parasect"] = 95,
["venonat"] = 52,
["venomoth"] = 49,
["diglett"] = 82,
["dugtrio"] = 83,
["meowth"] = 105,
["persian"] = 3,
["psyduck"] = 100,
["golduck"] = 99,
["mankey"] = 106,
["primeape"] = 103,
["growlithe"] = 109,
["arcanine"] = 91,
["poliwag"] = 111,
["poliwhirl"] = 212,
["poliwrath"] = 104,
["abra"] = 262,
["kadabra"] = 219,
["alakazam"] = 218,
["machop"] = 118,
["machoke"] = 113,
["machamp"] = 121,
["bellsprout"] = 250,
["weepinbell"] = 37,
["victreebel"] = 240,
["tentacool"] = 96,
["tentacruel"] = 108,
["geodude"] = 196,
["graveler"] = 247,
["golem"] = 116,
["ponyta"] = 16,
["rapidash"] = 2116,
["slowpoke"] = 75,
["slowbro"] = 2885,
["magnemite"] = 217,
["magneton"] = 223,
["farfetch'd"] = 57,
["doduo"] = 26,
["dodrio"] = 120,
["seel"] = 101,
["dewgong"] = 110,
["grimer"] = 214,
["muk"] = 47,
["shellder"] = 54,
["cloyster"] = 72,
["gastly"] = 48,
["haunter"] = 65,
["gengar"] = 244,
["onix"] = 248,
["drowzee"] = 94,
["hypno"] = 119,
["krabby"] = 112,
["kingler"] = 245,
["voltorb"] = 123,
["electrode"] = 125,
["exeggcute"] = 213,
["exeggutor"] = 46,
["cubone"] = 124,
["marowak"] = 197,
["hitmonlee"] = 20,
["hitmonchan"] = 38,
["lickitung"] = 11,
["koffing"] = 228,
["weezing"] = 231,
["rhyhorn"] = 77,
["rhydon"] = 200,
["chansey"] = 4,
["tangela"] = 18,
["kangaskhan"] = 198,
["horsea"] = 33,
["seadra"] = 276,
["goldeen"] = 274,
["seaking"] = 272,
["staryu"] = 42,
["starmie"] = 249,
["mr. mime"] = 246,
["scyther"] = 15,
["jynx"] = 282,
["electabuzz"] = 281,
["magmar"] = 76,
["pinsir"] = 53,
["tauros"] = 93,
["magikarp"] = 19,
["gyarados"] = 117,
["lapras"] = 193,
["ditto"] = 28,
["eevee"] = 102,
["vaporeon"] = 215,
["jolteon"] = 195,
["flareon"] = 14,
["porygon"] = 97,
["omanyte"] = 92,
["omastar"] = 192,
["kabuto"] = 98,
["kabutops"] = 164,
["aerodactyl"] = 10,
["snorlax"] = 51,
["articuno"] = 283,
["zapdos"] = 199,
["moltres"] = 265,
["dratini"] = 58,
["dragonair"] = 61,
["dragonite"] = 211,
["mewtwo"] = 34,
["mew"] = 9,
----------- SHINIES -----------
["shiny venusaur"] = 496,
["shiny charizard"] = 294,
["shiny blastoise"] = 495,
["shiny butterfree"] = 485,
["shiny beedrill"] = 483,
["shiny pidgeot"] = 573,
["shiny rattata"] = 512,
["shiny raticate"] = 519,
["shiny fearow"] = 649,
["shiny raichu"] = 511,
["shiny nidoking"] = 635,
["shiny ninetales"] = 1665,
["shiny zubat"] = 521,
["shiny golbat"] = 576,
["shiny oddish"] = 509,
["shiny vileplume"] = 636,
["shiny paras"] = 510,
["shiny parasect"] = 501,
["shiny venonat"] = 517,
["shiny venomoth"] = 484,
["shiny growlithe"] = 505,
["shiny arcanine"] = 493,
["shiny abra"] = 491,
["shiny alakazam"] = 574,
["shiny machamp"] = 1818,
["shiny tentacool"] = 502,
["shiny tentacruel"] = 489,
["shiny golem"] = 637,
["shiny magneton"] = 1671,
["shiny farfetch'd"] = 520,
["shiny dodrio"] = 1672,
["shiny grimer"] = 487,
["shiny muk"] = 488,
["shiny gengar"] = 546,
["shiny onix"] = 292,
["shiny hypno"] = 597,
["shiny krabby"] = 508,
["shiny kingler"] = 500,
["shiny voltorb"] = 518,
["shiny electrode"] = 516,
["shiny cubone"] = 578,
["shiny marowak"] = 579,
["shiny hitmonlee"] = 526,
["shiny hitmonchan"] = 486,
["shiny rhydon"] = 1573,
["shiny tangela"] = 580,
["shiny horsea"] = 507,
["shiny seadra"] = 515,
["shiny mr. mime"] = 1506,
["shiny scyther"] = 525,
["shiny jynx"] = 499,
["shiny electabuzz"] = 497,
["shiny magmar"] = 1779,
["shiny pinsir"] = 577,
["shiny tauros"] = 1821,
["shiny magikarp"] = 504,
["shiny gyarados"] = 528,
["shiny ditto"] = 549,
["shiny vaporeon"] = 596,
["shiny jolteon"] = 594,
["shiny flareon"] = 595,
["shiny snorlax"] = 548,
["shiny dratini"] = 506,
["shiny dragonair"] = 575,
}

typesEffectiveness = {
["normal"] = {weak = {"rock", "steel"}, non = {"ghost"}},
["fire"] = {super = {"bug", "grass", "ice", "steel"}, weak = {"dragon", "fire", "rock", "water"}},
["fighting"] = {super = {"dark", "ice", "normal", "rock", "steel"}, weak = {"bug", "fairy", "flying", "poison", "psychic"}, non = {"ghost"}},
["water"] = {super = {"fire", "ground", "rock"}, weak = {"dragon", "grass", "water"}},
["flying"] = {super = {"bug", "fighting", "grass"}, weak = {"electric", "rock", "steel"}},
["grass"] = {super = {"ground", "rock", "water"}, weak = {"bug", "dragon", "fire", "flying", "grass", "poison", "steel"}},
["poison"] = {super = {"fairy", "grass"}, weak = {"ghost", "ground", "poison", "rock"}, non = {"steel"}},
["electric"] = {super = {"flying", "water"}, weak = {"dragon", "electric", "grass"}, non = {"ground"}},
["ground"] = {super = {"electric", "fire", "poison", "rock", "steel"}, weak = {"bug", "grass"}, non = {"flying"}},
["psychic"] = {super = {"fighting", "poison"}, weak = {"psychic", "steel"}, non = {"dark"}},
["rock"] = {super = {"bug", "fire", "flying", "ice"}, weak = {"fighting", "ground", "steel"}},
["ice"] = {super = {"dragon", "flying", "grass", "ground"}, weak = {"fire", "ice", "steel", "water"}},
["bug"] = {super = {"dark", "grass", "psychic"}, weak = {"fairy", "fighting", "fire", "flying", "ghost", "poison", "steel"}},
["dragon"] = {super = {"dragon"}, weak = {"steel"}, non = {"fairy"}},
["ghost"] = {super = {"ghost", "psychic"}, weak = {"dark"}, non = {"normal"}},
["dark"] = {super = {"ghost", "psychic"}, weak = {"dark", "fairy", "fighting"}},
["steel"] = {super = {"fairy", "ice", "rock"}, weak = {"electric", "fire", "steel", "water"}},
["fairy"] = {super = {"dark", "dragon", "fighting"}, weak = {"fire", "poison", "steel"}},
}

function isInArray(tables, string)
  for i = 1, #tables do
    if tables[i] == string then
      return true
    end
  end
  return false
end

function getEffectiveness(type1, type2, effectiveness)
  local ret = {}
  for a,_ in pairs(typesEffectiveness) do
    local multiplier = 1
    if typesEffectiveness[a].super and isInArray(typesEffectiveness[a].super, type1) then
      multiplier = type2 and multiplier * 2 or multiplier * 4
    end
    if typesEffectiveness[a].super and type2 and isInArray(typesEffectiveness[a].super, type2) then
      multiplier = multiplier * 2
    end
    if typesEffectiveness[a].weak and isInArray(typesEffectiveness[a].weak, type1) then    
      multiplier = type2 and multiplier / 2 or multiplier / 4
    end
    if typesEffectiveness[a].weak and type2 and isInArray(typesEffectiveness[a].weak, type2) then
      multiplier = multiplier / 2
    end
    if typesEffectiveness[a].non and isInArray(typesEffectiveness[a].non, type1) then
      multiplier = 0
    end
    if typesEffectiveness[a].non and type2 and isInArray(typesEffectiveness[a].non, type2) then
      multiplier = 0
    end
    if multiplier == effectiveness then
      table.insert(ret, a..'-')
    end
  end

  return table.concat(ret)
end

function doCorrectString(str)
  local name = str:explode(' ')
  local final = {}
  for _, s in ipairs(name) do
    table.insert(final, s:sub(1, 1):upper()..s:sub(2, #s):lower())
  end
  return table.concat(final, (name[2] and ' ' or ''))
end

function isPassive(skill)
  for i = 1, #pokemonPassives do
    if pokemonPassives[i] == skill then
      return true
    end
  end
  return false
end

function getPokemonSkills(name)
  local str = ""
  for a, b in pairs(pokemonSkills) do
    for i = 1, #b do
      if(b[i] == name) then
        if not isPassive(a) then
          str = str .. (str == "" and "" or ", ") .. a
        end
      end
    end
  end
  if str == "" then
    str = "None"
  end
  return doCorrectString(str)
end

function getPokemonIdByName(name)
  for i = 1, #pokemonId do
    if pokemonId[i] == name then
      return i
    end
  end
  return 1
end

function getPokemonNameByOutfit(outfit)
  for a, b in pairs(pokemonsOutfit) do
    if b == outfit then
      return doCorrectString(a)
    end
  end
  return 'Bulbasaur'
end
